# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c47e6da5e5122d12999e4ad74074d27f579c5752e457fa7390a6871dcc8869d7fd97d033d7f927d1de267725ae34f9b983c0420656eced8ba6d873d763c9525c

test:
  secret_key_base: d38e6f72c4e8e58dc26f9be6adb74c72b6db7d23e07bfbdf1d4b4a1bfa6165823843829bda533121941b983e8db383444fd81a8ed33e47e8e24596489773fbc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
